//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.RentalRepairs.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.RentalRepairs.Infrastructure.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request Registered.
        /// </summary>
        internal static string Property2TenantOnRequestReceivedMessageSubjectTemplate {
            get {
                return ResourceManager.GetString("Property2TenantOnRequestReceivedMessageSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi [TenantFullName], /r/n Your service request from [RequestDate] has been registered. Sincerely, /r/n [PropertyName].
        /// </summary>
        internal static string Property2TenantOnRequestReceivedMessageTemplate {
            get {
                return ResourceManager.GetString("Property2TenantOnRequestReceivedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request Declined.
        /// </summary>
        internal static string Property2TenantOnRequestRejectedMessageSubjectTemplate {
            get {
                return ResourceManager.GetString("Property2TenantOnRequestRejectedMessageSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi [TenantFullName], /r/n Unfortunately, we cannot start your service request from [RequestDate]. Please call us [PropertyPhone] at your convenience. /r/n  Sincerely, /r/n [PropertyName].
        /// </summary>
        internal static string Property2TenantOnRequestRejectedMessageTemplate {
            get {
                return ResourceManager.GetString("Property2TenantOnRequestRejectedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new work order.
        /// </summary>
        internal static string Property2WorkerOnRequestScheduledMessageSubjectTemplate {
            get {
                return ResourceManager.GetString("Property2WorkerOnRequestScheduledMessageSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello [WorkerFullName], /r/n A new work order is scheduled for you. Please visit [WorkOrderPageUrl] for details. Sincerely, /r/n [PropertyName].
        /// </summary>
        internal static string Property2WorkerOnRequestScheduledMessageTemplate {
            get {
                return ResourceManager.GetString("Property2WorkerOnRequestScheduledMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work order completed.
        /// </summary>
        internal static string Worker2PropertyWorkDoneMessageSubjectTemplate {
            get {
                return ResourceManager.GetString("Worker2PropertyWorkDoneMessageSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello [SuperintendentFullName], /r/n I completed work order [WorkOrderNumber]. For report, please visit [WorkReportPageUrl].  Sincerely, /r/n [WorkerFullName].
        /// </summary>
        internal static string Worker2PropertyWorkDoneMessageTemplate {
            get {
                return ResourceManager.GetString("Worker2PropertyWorkDoneMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work can&apos;t be completed.
        /// </summary>
        internal static string Worker2PropertyWorkIncompleteMessageSubjectTemplate {
            get {
                return ResourceManager.GetString("Worker2PropertyWorkIncompleteMessageSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello [SuperintendentFullName], /r/n Unfortunately, the work order N[WorkOrderNumber] from [WorkOrderDate] can&apos;t be completed. For the report, please visit [WorkReportPageUrl].  Sincerely, /r/n [WorkerFullName].
        /// </summary>
        internal static string Worker2PropertyWorkIncompleteMessageTemplate {
            get {
                return ResourceManager.GetString("Worker2PropertyWorkIncompleteMessageTemplate", resourceCulture);
            }
        }
    }
}
